name: Back End

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '.github/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Application
        working-directory: api
        run: |

          ./gradlew clean build
      
      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: api/build/libs/api.jar

  build-image:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Build Image
        working-directory: api
        run: |

          docker build -t api . 